version: "3"

services:
  sonarqube:
    container_name: sonarqube
    image: hub4rpi64/sonarqube:8.3.1.34397
    ports: 
      - "9090:9090"
    network_mode: bridge
    environment:
      ServerIP: '192.168.0.248'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
